
import { PodcastEpisode, Translation, Language } from './types';

export const ZUZZI_HERO_IMAGE = "/mainhero.jpg"; 

export const TRANSLATIONS: Record<Language, Translation> = {
  'cs-CZ': {
    nav_home: 'Domů',
    nav_episodes: 'Epizody',
    nav_about: 'O Zuzaně',
    nav_contact: 'Kontakt',
    nav_crm: 'CRM Login',
    hero_title: 'Podcast #1 pro ženy, které chtějí víc',
    hero_subtitle: 'Poslech podcastu ICONIC je jako káva s mentorkou, která tě nenechá hrát při zdi. Zuzana Husárová ti ukáže, jak být svá a ikonická.',
    hero_cta: 'Poslechnout nejnovější díl',
    hero_kicker: 'The Iconic Podcast',
    hero_spotify_btn: 'Spotify',
    latest_episodes: 'Nejnovější Epizody',
    search_placeholder: 'Hledat epizodu...',
    no_episodes_found: 'Nebyly nalezeny žádné epizody.',
    filter_all: 'Vše',
    listen_on: 'Poslouchejte na',
    episode_about_title: 'O epizodě',
    episode_description_suffix: 'Poslouchejte tuto epizodu a zjistěte více o tom, jak být ikonická ve svém podnikání i osobním životě. Zuzana sdílí své osobní zkušenosti, pády i vzestupy.',
    listen_button: 'Poslechnout',
    contact_title: 'Kontaktujte nás',
    contact_subtitle: 'Máte dotaz, zájem o spolupráci nebo feedback? Napište nám.',
    contact_info_title: 'Kontaktní údaje',
    contact_email: 'Email',
    contact_phone: 'Telefon',
    contact_instagram: 'Instagram',
    contact_success_title: 'Zpráva odeslána!',
    contact_success_msg: 'Děkujeme za váš zájem. Brzy se vám ozveme.',
    form_name: 'Jméno',
    form_email: 'Email',
    form_phone: 'Telefon',
    form_message: 'Zpráva',
    form_submit: 'Odeslat Zprávu',
    footer_desc: 'Podcast pro ženy, které chtějí víc. Business, mindset a lifestyle bez kompromisů.',
    footer_menu: 'Menu',
    footer_contact: 'Kontakt',
    footer_location: 'Praha, Česká republika',
    footer_rights: 'Všechna práva vyhrazena.',
    chatbot_welcome: 'Ahoj! Jsem AI asistentka ICONIC. Jak ti mohu pomoci nastartovat tvou cestu?',
    chatbot_starters: ["Chci nastartovat byznys 🚀", "Hledám inspiraci ✨", "Spolupráce se Zuzkou 🤝", "Jak na sebedůvěru? 💖"],
    crm_title: 'ICONIC CRM Dashboard',
    crm_leads: 'Získané Kontakty',
    placeholder_loading: 'Načítám...',
    newsletter_title: 'Přidej se do ICONIC klubu',
    newsletter_desc: 'Získej týdenní dávku inspirace a VIP pozvánky přímo do e-mailu.',
    newsletter_placeholder: 'Tvůj email',
    newsletter_btn: 'Chci být u toho',
    newsletter_success: 'Vítej v klubu! 🥂',
    guest_modal_title: 'Chceš být vidět?',
    guest_modal_desc: 'Staň se hostem našeho podcastu a ukaž světu svou vizi a podnikatelský přesah.',
    guest_modal_btn: 'Mám zájem být hostem',
    guest_modal_success: 'Skvělé! Brzy se ti ozveme.'
  },
  'en-US': {
    nav_home: 'Home',
    nav_episodes: 'Episodes',
    nav_about: 'About',
    nav_contact: 'Contact',
    nav_crm: 'CRM Login',
    hero_title: 'The #1 Podcast for Women Who Want More',
    hero_subtitle: 'Listening to the Iconic Podcast is like having coffee with a mentor who wont let you play small. Zuzana Husarova shows you how to be yourself and iconic.',
    hero_cta: 'Listen to Latest',
    hero_kicker: 'The Iconic Podcast',
    hero_spotify_btn: 'Spotify',
    latest_episodes: 'Latest Episodes',
    search_placeholder: 'Search episodes...',
    no_episodes_found: 'No episodes found.',
    filter_all: 'All',
    listen_on: 'Listen on',
    episode_about_title: 'About Episode',
    episode_description_suffix: 'Listen to this episode and find out more about how to be iconic in your business and personal life. Zuzana shares her personal experiences, ups and downs.',
    listen_button: 'Listen',
    contact_title: 'Contact Us',
    contact_subtitle: 'Have a question, interest in cooperation, or feedback? Write to us.',
    contact_info_title: 'Contact Info',
    contact_email: 'Email',
    contact_phone: 'Phone',
    contact_instagram: 'Instagram',
    contact_success_title: 'Message Sent!',
    contact_success_msg: 'Thank you for your interest. We will be in touch soon.',
    form_name: 'Name',
    form_email: 'Email',
    form_phone: 'Phone',
    form_message: 'Message',
    form_submit: 'Send Message',
    footer_desc: 'A podcast for women who want more. Business, mindset, and lifestyle without compromise.',
    footer_menu: 'Menu',
    footer_contact: 'Contact',
    footer_location: 'Prague, Czech Republic',
    footer_rights: 'All rights reserved.',
    chatbot_welcome: 'Hi! I am the ICONIC AI assistant. How can I help you start your journey?',
    chatbot_starters: ["Start a business 🚀", "Looking for inspiration ✨", "Work with Zuzka 🤝", "Boost confidence 💖"],
    crm_title: 'ICONIC CRM Dashboard',
    crm_leads: 'Captured Leads',
    placeholder_loading: 'Loading...',
    newsletter_title: 'Join the ICONIC Club',
    newsletter_desc: 'Get your weekly dose of inspiration and VIP invites straight to your inbox.',
    newsletter_placeholder: 'Your email',
    newsletter_btn: 'Join Now',
    newsletter_success: 'Welcome to the club! 🥂',
    guest_modal_title: 'Want to be seen?',
    guest_modal_desc: 'Become a guest on our podcast and show the world your vision and entrepreneurial reach.',
    guest_modal_btn: 'I want to be a guest',
    guest_modal_success: 'Great! We will contact you soon.'
  },
  'es-MX': {
    nav_home: 'Inicio',
    nav_episodes: 'Episodios',
    nav_about: 'Sobre mí',
    nav_contact: 'Contacto',
    nav_crm: 'Acceso CRM',
    hero_title: 'El Podcast #1 para Mujeres Ambiciosas',
    hero_subtitle: 'Escuchar el Podcast Iconic es como tomar un café con una mentora que no te dejará jugar en pequeño. Zuzana Husarova te enseña a ser tú misma e icónica.',
    hero_cta: 'Escuchar lo último',
    hero_kicker: 'The Iconic Podcast',
    hero_spotify_btn: 'Spotify',
    latest_episodes: 'Últimos Episodios',
    search_placeholder: 'Buscar episodio...',
    no_episodes_found: 'No se encontraron episodios.',
    filter_all: 'Todos',
    listen_on: 'Escúchalo en',
    episode_about_title: 'Sobre el episodio',
    episode_description_suffix: 'Escucha este episodio y descubre más sobre cómo ser icónica en tu negocio y vida personal. Zuzana comparte sus experiencias personales, altibajos.',
    listen_button: 'Escuchar',
    contact_title: 'Contáctanos',
    contact_subtitle: '¿Tienes una pregunta, interés en colaborar o comentarios? Escríbenos.',
    contact_info_title: 'Información de contacto',
    contact_email: 'Correo',
    contact_phone: 'Teléfono',
    contact_instagram: 'Instagram',
    contact_success_title: '¡Mensaje enviado!',
    contact_success_msg: 'Gracias por tu interés. Nos pondremos en contacto pronto.',
    form_name: 'Nombre',
    form_email: 'Correo',
    form_phone: 'Teléfono',
    form_message: 'Mensaje',
    form_submit: 'Enviar Mensaje',
    footer_desc: 'Un podcast para mujeres que quieren más. Negocios, mentalidad y estilo de vida sin compromisos.',
    footer_menu: 'Menú',
    footer_contact: 'Contacto',
    footer_location: 'Praga, República Checa',
    footer_rights: 'Todos los derechos reservados.',
    chatbot_welcome: '¡Hola! Soy la asistente IA de ICONIC. ¿Cómo puedo ayudarte a comenzar tu viaje?',
    chatbot_starters: ["Iniciar un negocio 🚀", "Busco inspiración ✨", "Trabajar con Zuzka 🤝", "Aumentar confianza 💖"],
    crm_title: 'Panel CRM ICONIC',
    crm_leads: 'Prospectos Capturados',
    placeholder_loading: 'Cargando...',
    newsletter_title: 'Únete al Club ICONIC',
    newsletter_desc: 'Recibe tu dosis semanal de inspiración e invitaciones VIP directamente en tu correo.',
    newsletter_placeholder: 'Tu correo',
    newsletter_btn: 'Únete Ahora',
    newsletter_success: '¡Bienvenida al club! 🥂',
    guest_modal_title: '¿Quieres ser vista?',
    guest_modal_desc: 'Sé una invitada en nuestro podcast y muestra al mundo tu visión y alcance empresarial.',
    guest_modal_btn: 'Quiero ser invitada',
    guest_modal_success: '¡Genial! Te contactaremos pronto.'
  }
};

// Real links provided by the user
const LINKS = {
  spotify: 'https://open.spotify.com/show/5TNpvLzycWShFtP0uu39bE',
  youtube: 'https://www.youtube.com/@ZuzziHusarova',
  apple: 'https://podcasts.apple.com/cz/podcast/iconic-podcast-by-zuzzi-mentor/id1831207868?l=cs',
  amazon: 'https://www.amazon.com/ICONIC-Podcast-by-Zuzzi-Mentor/dp/B0FLDMHDQM'
};

export const PRICING_PLANS = [
  { name: 'Mentoring Start', price: '4.990 Kč', recommended: false },
  { name: 'Business Grow', price: '14.990 Kč', recommended: true },
  { name: 'Iconic Brand VIP', price: '39.990 Kč', recommended: false },
];

export const PODCAST_EPISODES: PodcastEpisode[] = [
  {
    id: '15',
    title: 'EP 15: O tomhle přístupu k rodičovství potřebuješ slyšet | Tereza Veselá',
    description: 'Jak zvládat emoce a nezbláznit se? Tereza Veselá z Matcastu sdílí, proč je mateřství největší školou seberozvoje a proč dítě nepotřebuje animátora, ale tvou pravdivou přítomnost.',
    duration: '32 min',
    date: '2024-12-03',
    imageUrl: '/ep15.jpg',
    videoUrl: 'sCIGYzgfXNA',
    tags: ['Lifestyle', 'Mindset'],
    platformLinks: { 
      spotify: 'https://open.spotify.com/episode/5yqjO88j3vITLxv6xOTY1P', 
      youtube: 'https://www.youtube.com/watch?v=sCIGYzgfXNA', 
      apple: LINKS.apple 
    }
  },
  {
    id: '14',
    title: 'EP 14: Jak překonat strach z prodeje',
    description: 'Prodej je služba. V této epizodě se podíváme na to, jak přenastavit svou mysl, abyste prodávaly s lehkostí a elegancí.',
    duration: '42 min',
    date: '2024-06-10',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1olohtrry9E26ZY-F0o7Vdqe7XCHvI90I',
    videoUrl: 'UfJvyeQorH4',
    tags: ['Business', 'Mindset'],
    platformLinks: { spotify: LINKS.spotify, youtube: LINKS.youtube, apple: LINKS.apple }
  },
  {
    id: '13',
    title: 'EP 13: Budování osobní značky v roce 2024',
    description: 'Osobní značka je vaše nejcennější aktivum. Jak být autentická a přitahovat ty správné klienty bez nutnosti se přetvařovat?',
    duration: '38 min',
    date: '2024-05-28',
    imageUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&q=80&w=1000',
    videoUrl: 'UfJvyeQorH4',
    tags: ['Business', 'Lifestyle'],
    platformLinks: { spotify: LINKS.spotify, youtube: LINKS.youtube, apple: LINKS.apple }
  },
  {
    id: '12',
    title: 'EP 12: Finanční hojnost a nastavení mysli',
    description: 'Peníze jsou energie. Zuzana rozebírá bloky, které nám brání vydělávat více, a dává praktické tipy pro finanční svobodu.',
    duration: '45 min',
    date: '2024-05-15',
    imageUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&q=80&w=1000',
    videoUrl: 'UfJvyeQorH4',
    tags: ['Finance', 'Mindset'],
    platformLinks: { spotify: LINKS.spotify, youtube: LINKS.youtube, apple: LINKS.apple }
  },
  {
    id: '11',
    title: 'EP 11: Jak skloubit byznys a rodinu',
    description: 'Je možné mít úspěšnou kariéru a zároveň být skvělou mámou? Otevřený rozhovor o work-life balance a prioritách.',
    duration: '50 min',
    date: '2024-05-01',
    imageUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&q=80&w=1000',
    videoUrl: 'UfJvyeQorH4',
    tags: ['Lifestyle', 'Business'],
    platformLinks: { spotify: LINKS.spotify, youtube: LINKS.youtube, apple: LINKS.apple }
  },
  {
    id: '10',
    title: 'EP 10: Začínáme podnikat: První kroky',
    description: 'Od nápadu k realizaci. Co všechno potřebujete vědět, než se pustíte do vlastního projektu? Průvodce pro začínající podnikatelky.',
    duration: '35 min',
    date: '2024-04-18',
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=1000',
    videoUrl: 'UfJvyeQorH4',
    tags: ['Business'],
    platformLinks: { spotify: LINKS.spotify, youtube: LINKS.youtube, apple: LINKS.apple }
  },
  {
    id: '9',
    title: 'EP 09: Sebedůvěra jako klíč k úspěchu',
    description: 'Jak si věřit, i když o sobě pochybujete. Techniky pro posílení sebevědomí a překonání imposter syndromu.',
    duration: '40 min',
    date: '2024-04-05',
    imageUrl: 'https://images.unsplash.com/photo-1627483297886-49710ae1fc28?auto=format&fit=crop&q=80&w=1000',
    videoUrl: 'UfJvyeQorH4',
    tags: ['Mindset'],
    platformLinks: { spotify: LINKS.spotify, youtube: LINKS.youtube, apple: LINKS.apple }
  },
  {
    id: '8',
    title: 'EP 08: Marketingové strategie pro rok 2024',
    description: 'Co funguje na sociálních sítích dnes? Změny algoritmů, trendy a jak být vidět bez placené reklamy.',
    duration: '48 min',
    date: '2024-03-22',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1000',
    videoUrl: 'UfJvyeQorH4',
    tags: ['Business', 'Marketing'],
    platformLinks: { spotify: LINKS.spotify, youtube: LINKS.youtube, apple: LINKS.apple }
  },
  {
    id: '7',
    title: 'EP 07: Příběh mé cesty',
    description: 'Jak jsem začínala já? Otevřená zpověď o mých začátcích, chybách a lekcích, které mě formovaly.',
    duration: '55 min',
    date: '2024-03-10',
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1000',
    videoUrl: 'UfJvyeQorH4',
    tags: ['Lifestyle', 'Mindset'],
    platformLinks: { spotify: LINKS.spotify, youtube: LINKS.youtube, apple: LINKS.apple }
  }
];
